[workspace]
members = ["gm-addr-extract-lib", "gm-addr-extract", "gm-addr-extract-ffi"]
default-members = ["gm-addr-extract"]
resolver = "2"

[profile.release]
codegen-units = 1
panic = "abort"
lto = true
strip = true
