[package]
name = "gm-addr-extract-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
disarm64 = { git = "https://github.com/mokurin000/disarm64.git", branch = "move-goblin" }
elf = "0.7.4"
itertools = "0.14.0"
